---
- name: Downloading the package
  get_url:
    url: "https://s3-eu-west-1.amazonaws.com/devops-assesment/countries-assembly-1.0.1.jar"
    dest: /app/countries-assembly-1.0.1.jar
    mode: 0775

- name: Running the service
  shell: nohup java -jar /app/countries-assembly-1.0.1.jar </dev/null >/dev/null 2>&1 &
  async: 2592000
  pool: 0

- name: Install reverse proxy
  apt:
    name: nginx
    state: latest

- name: Configure reverse proxy
  template:
    src: vhost.j2
    dest: /etc/nginx/sites-available/default
  notify: Nginx Start

